language: csharp
os: windows
mono: none

branches:
  only:
  - master

before_install:
  - choco install dotnet-5.0-sdk
  - powershell Set-ExecutionPolicy Unrestricted
install:
  - dotnet restore
script:
  - dotnet build -c Release Monstromatic/Monstromatic.csproj
after_success:
  - powershell ./.travis/dotnet-publish.ps1
  - powershell ./.travis/get-project-version.ps1
  - powershell Compress-Archive -Path Monstromatic/bin/Release/net5.0/win-x64/publish/Monstromatic.exe -DestinationPath Monstromatic.zip
  - curl -F caption="The new release is here!" -F name=document -F document=@Monstromatic.zip -H "Content-Type:multipart/form-data" "https://api.telegram.org/bot%TELEGRAM_BOT_TOKEN%/sendDocument?chat_id=%TELEGRAM_CHAT_ID%"

