language: csharp
os: windows
mono: none

branches:
  only:
  - master

before_install:
  - choco install dotnet-5.0-sdk
  - powershell Set-ExecutionPolicy Unrestricted
install:
  - dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
  - dotnet restore
script:
  - dotnet build -c Release Monstromatic/Monstromatic.csproj
after_success:
  - powershell ./.travis/dotnet-publish.ps1
  - powershell ./.travis/get-project-version.ps1 > version.txt
  - powershell ./.travis/compress-artifacts.ps1
  - powershell ./.travis/send-telegram-notification.ps1

