language: csharp
os: windows
mono: none
before_install:
  - choco install dotnet-5.0-sdk
install:
  - dotnet restore
script:
  - dotnet build Monstromatic/Monstromatic.csproj -c Release
  - dotnet publish Monstromatic/Monstromatic.csproj -c Release -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeAllContentForSelfExtract=true
after_script:
# - dotnet publish -c Release -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeAllContentForSelfExtract=true
# - dotnet test ./ThinkingHome.NooLite.Tests -c Release -f net5.0
