language: csharp
os: windows
mono: none

branches:
  only:
  - master

before_install:
  - choco install dotnet-5.0-sdk
install:
  - dotnet restore
script:
  - dotnet build -c Release Monstromatic/Monstromatic.csproj
# - dotnet test ./ThinkingHome.NooLite.Tests -c Release -f net5.0
after_script:
  - ./.travis/dotnet-publish.ps1
  - ./.travis/get-project-version.ps1
  - Compress-Archive -Path Monstromatic/bin/Release/net5.0/win-x64/publish/Monstromatic.exe -DestinationPath Monstromatic-$env:csproj_version.zip
  - wsl .travis/publish-to-telegram.sh $env:TELEGRAM_BOT_TOKEN $env:TELEGRAM_CHAT_ID Monstromatic-$env:csproj_version.zip "The new release is here!"

