os: linux
dist: bionic
language: csharp
mono: none
dotnet: 5.0.100
before_script:
  - dotnet restore
script:
  - dotnet build ./Monstromatic/Monstromatic.csproj -c Release
after_script:
  - dotnet publish -c Release -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeAllContentForSelfExtract=true
#  - dotnet test ./ThinkingHome.NooLite.Tests -c Release -f net5.0
