---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

env:
  DOTNET_VERSION: 6.0.x

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Ceckout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    name: Publish artifact
    needs: build-and-test
    runs-on: windows-latest

    steps:
      - name: Ceckout repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publish
        run: dotnet publish .\Monstromatic\Monstromatic.csproj -c Release -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o publish
      - name: Zip Artifacts  
        run: powershell Compress-Archive .\publish\Monstromatic.exe Monstromatic.zip
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            Monstromatic.zip